# Generated by Django 5.1.1 on 2025-05-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='question',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
